version: '3'
services:
  server:
    build: .
    command: sleep infinity
    volumes:
      - .:/workspace
      - ~/.ssh:/root/.ssh-localhost:ro
  scheduler:
    build: .
    command: sleep infinity
    volumes:
      - .:/workspace