version: '3'
services:
  web:
    build: .
    image: friendly-web
    ports:
      - 8001:8000
    networks:
      - friendly-net
  redis:
    image: redis
    ports:
      - 6380:6379
    volumes:
      - ~/data/friendly-hello/redis:/data
    command: redis-server --appendonly yes
    networks:
      - friendly-net
networks:
  friendly-net: